apiVersion: v1
kind: Service
metadata:
  name: spark-master
spec:
  selector:
    component: spark-master
  ports:
    - name: ui
      port: 8080
      targetPort: 8080
    - name: spark
      port: 6000
      targetPort: 6000
  