apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-master
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spark-master
  template:
    metadata:
      labels: # Add labels here to match the selector
        app: spark-master
    spec:
      containers:
        - name: spark-master
          image: apache/spark:latest
          imagePullPolicy: Always
          command:
            ["/spark-master"]
          ports:
            - containerPort: 6000
            - containerPort: 8080
          env:
            - name: SPARK_LOCAL_IP
              value: "0.0.0.0"
      restartPolicy: Always
